"""pessoas mudar tipo de data_nascimento, e aumentar local_nascimento

Revision ID: 03b2cdc51ad8
Revises: a4c324a63c48
Create Date: 2025-10-18 02:59:03.048413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03b2cdc51ad8'
down_revision = 'a4c324a63c48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pessoas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('local_nascimento', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('com_foto', sa.Boolean(), server_default='false', nullable=False))
        batch_op.alter_column('data_nascimento',
               existing_type=sa.DATETIME(),
               type_=sa.Date(),
               existing_nullable=True)
        batch_op.drop_column('nacionalidade')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pessoas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nacionalidade', sa.VARCHAR(length=50), nullable=True))
        batch_op.alter_column('data_nascimento',
               existing_type=sa.Date(),
               type_=sa.DATETIME(),
               existing_nullable=True)
        batch_op.drop_column('com_foto')
        batch_op.drop_column('local_nascimento')

    # ### end Alembic commands ###
