"""Inclusao da data de falecimento

Revision ID: 27d7a2a57541
Revises: 6d0153161c40
Create Date: 2025-10-20 18:45:27.286460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27d7a2a57541'
down_revision = '6d0153161c40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pessoas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_falecimento', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pessoas', schema=None) as batch_op:
        batch_op.drop_column('data_falecimento')

    # ### end Alembic commands ###
