"""2FA para autenticação

Revision ID: 285c2abd169d
Revises: d95015f985b1
Create Date: 2025-10-10 01:28:16.504181

"""
from alembic import op
import sqlalchemy as sa

import app.models.custom_types

# revision identifiers, used by Alembic.
revision = '285c2abd169d'
down_revision = 'd95015f985b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('usa_2fa', sa.Boolean(), server_default='false', nullable=False))
        batch_op.add_column(sa.Column('_otp_secret', app.models.custom_types.EncryptedType(length=500), nullable=True))
        batch_op.add_column(sa.Column('ultimo_otp', sa.String(length=6), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_column('ultimo_otp')
        batch_op.drop_column('_otp_secret')
        batch_op.drop_column('usa_2fa')

    # ### end Alembic commands ###
