"""adicionar campo dta_ultima_alteracao_senha

Revision ID: 58a0f49e0e74
Revises: 81ecdc930202
Create Date: 2025-10-06 20:58:06.221801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58a0f49e0e74'
down_revision = '81ecdc930202'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dta_ultima_alteracao_senha', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_column('dta_ultima_alteracao_senha')

    # ### end Alembic commands ###
