"""Migracao inicial

Revision ID: 58d55d48864e
Revises: 
Create Date: 2025-10-03 00:16:32.495220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58d55d48864e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nome', sa.String(length=60), nullable=False),
    sa.Column('email_normalizado', sa.String(length=180), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('ativo', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('dta_validacao_email', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usuarios_email_normalizado'), ['email_normalizado'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuarios_email_normalizado'))

    op.drop_table('usuarios')
    # ### end Alembic commands ###
