"""Acrescetnar descricao da funcao tecnica

Revision ID: 6d0153161c40
Revises: 81eaf112e462
Create Date: 2025-10-18 17:13:29.898972

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d0153161c40'
down_revision = '81eaf112e462'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('funcoes_tecnicas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descricao', sa.String(length=1024), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('funcoes_tecnicas', schema=None) as batch_op:
        batch_op.drop_column('descricao')

    # ### end Alembic commands ###
