"""Add CASCADE to foreign keys with explicit constraint names

Revision ID: 865e4c90dc10
Revises: 27d7a2a57541
Create Date: 2025-10-26 02:04:53.396549

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '865e4c90dc10'
down_revision = '27d7a2a57541'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Para SQLite, batch_alter_table com recreate='always' vai recriar a tabela
    # com as novas foreign keys automaticamente

    with op.batch_alter_table('atuacoes', schema=None, recreate='always') as batch_op:
        pass  # A recriação com as novas FKs acontece automaticamente

    with op.batch_alter_table('avaliacoes', schema=None, recreate='always') as batch_op:
        pass  # A recriação com as novas FKs acontece automaticamente

    with op.batch_alter_table('equipes_tecnicas', schema=None, recreate='always') as batch_op:
        pass  # A recriação com as novas FKs acontece automaticamente

    with op.batch_alter_table('filmes_generos', schema=None, recreate='always') as batch_op:
        pass  # A recriação com as novas FKs acontece automaticamente

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Para reverter, precisamos remover ondelete='CASCADE' das FKs
    # Isso requer recriar as tabelas novamente em SQLite

    # NOTA: O downgrade remove o CASCADE, mas mantém os constraint names
    # Para voltar totalmente ao estado anterior (sem names), seria necessário
    # remover os models do código e gerar nova migration

    pass  # Por enquanto, não fazemos downgrade (CASCADE é uma melhoria)

    # ### end Alembic commands ###
