"""Filmes, pessoas e relacionamentos

Revision ID: a4c324a63c48
Revises: e8394aa11bdc
Create Date: 2025-10-17 01:06:07.762436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4c324a63c48'
down_revision = 'e8394aa11bdc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('filmes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('titulo_original', sa.String(length=180), nullable=False),
    sa.Column('titulo_portugues', sa.String(length=180), nullable=True),
    sa.Column('ano_lancamento', sa.Integer(), nullable=True),
    sa.Column('lancado', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('duracao_minutos', sa.Integer(), nullable=True),
    sa.Column('sinopse', sa.Text(), nullable=True),
    sa.Column('orcamento_milhares', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('faturamento_lancamento_milhares', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('com_poster', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('poster_base64', sa.Text(), nullable=True),
    sa.Column('poster_mime', sa.String(length=129), nullable=True),
    sa.Column('trailer_youtube', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('funcoes_tecnicas',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('ativo', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('generos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nome', sa.String(length=40), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=True),
    sa.Column('ativo', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('pessoas',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('data_nascimento', sa.DateTime(timezone=True), nullable=True),
    sa.Column('nacionalidade', sa.String(length=50), nullable=True),
    sa.Column('biografia', sa.Text(), nullable=True),
    sa.Column('foto_base64', sa.Text(), nullable=True),
    sa.Column('foto_mime', sa.String(length=129), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('atores',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('pessoa_id', sa.Uuid(), nullable=False),
    sa.Column('nome_artistico', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['pessoa_id'], ['pessoas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pessoa_id')
    )
    op.create_table('avaliacoes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('filme_id', sa.Uuid(), nullable=False),
    sa.Column('usuario_id', sa.Uuid(), nullable=False),
    sa.Column('nota', sa.Integer(), nullable=False),
    sa.Column('comentario', sa.Text(), nullable=True),
    sa.Column('recomendaria', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['filme_id'], ['filmes.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('filme_id', 'usuario_id', name='uq_filme_usuario')
    )
    op.create_table('equipes_tecnicas',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('filme_id', sa.Uuid(), nullable=False),
    sa.Column('pessoa_id', sa.Uuid(), nullable=False),
    sa.Column('funcao_tecnica_id', sa.Uuid(), nullable=False),
    sa.Column('creditado', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['filme_id'], ['filmes.id'], ),
    sa.ForeignKeyConstraint(['funcao_tecnica_id'], ['funcoes_tecnicas.id'], ),
    sa.ForeignKeyConstraint(['pessoa_id'], ['pessoas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('filme_id', 'pessoa_id', 'funcao_tecnica_id', name='uq_filme_pessoa_funcao')
    )
    op.create_table('filmes_generos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('filme_id', sa.Uuid(), nullable=False),
    sa.Column('genero_id', sa.Uuid(), nullable=False),
    sa.Column('primario', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['filme_id'], ['filmes.id'], ),
    sa.ForeignKeyConstraint(['genero_id'], ['generos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('filme_id', 'genero_id', name='uq_filme_genero')
    )
    op.create_table('atuacoes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('filme_id', sa.Uuid(), nullable=False),
    sa.Column('ator_id', sa.Uuid(), nullable=False),
    sa.Column('personagem', sa.String(length=100), nullable=False),
    sa.Column('protagonista', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('creditado', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('tempo_de_tela_minutos', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['ator_id'], ['atores.id'], ),
    sa.ForeignKeyConstraint(['filme_id'], ['filmes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('filme_id', 'ator_id', 'personagem', name='uq_filme_ator_personagem')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('atuacoes')
    op.drop_table('filmes_generos')
    op.drop_table('equipes_tecnicas')
    op.drop_table('avaliacoes')
    op.drop_table('atores')
    op.drop_table('pessoas')
    op.drop_table('generos')
    op.drop_table('funcoes_tecnicas')
    op.drop_table('filmes')
    # ### end Alembic commands ###
