"""Suporte a foto do usuario

Revision ID: a804d406b10c
Revises: 58a0f49e0e74
Create Date: 2025-10-09 18:54:07.299218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a804d406b10c'
down_revision = '58a0f49e0e74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('com_foto', sa.Boolean(), server_default='false', nullable=False))
        batch_op.add_column(sa.Column('foto_base64', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('avatar_base64', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('foto_mime', sa.String(length=32), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_column('foto_mime')
        batch_op.drop_column('avatar_base64')
        batch_op.drop_column('foto_base64')
        batch_op.drop_column('com_foto')

    # ### end Alembic commands ###
