"""Códigos de 2FA reserva

Revision ID: d95015f985b1
Revises: a804d406b10c
Create Date: 2025-10-09 23:09:14.244270

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd95015f985b1'
down_revision = 'a804d406b10c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backup2fa',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('hash_codigo', sa.String(length=256), nullable=False),
    sa.Column('usuario_id', sa.Uuid(), nullable=False),
    sa.Column('utilizado', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('dta_uso', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dta_para_remocao', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('backup2fa', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_backup2fa_usuario_id'), ['usuario_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('backup2fa', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_backup2fa_usuario_id'))

    op.drop_table('backup2fa')
    # ### end Alembic commands ###
