"""Aumento do tamannho do mimetype (RFC6838)

Revision ID: e8394aa11bdc
Revises: 3dd0544d3244
Create Date: 2025-10-16 22:59:04.669595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8394aa11bdc'
down_revision = '3dd0544d3244'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.alter_column('foto_mime',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=129),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.alter_column('foto_mime',
               existing_type=sa.String(length=129),
               type_=sa.VARCHAR(length=32),
               existing_nullable=True)

    # ### end Alembic commands ###
